
//Interface generated by psoting the data of our API into the web page json2ts
// http://json2ts.com/

//Biketours interface
export interface Biketours {
    id: number;
    title: string;
    description: string;
    imageURL: string;
    price: number;
    guide: string;
    coach: string;
    bycicleRental: string;
    availability: string;
    tags: string[];
    type: string;
    duration: string;
    routeMap: string;
} 

//Tourism interface
export interface Tourism {
    id: number;
    title: string;
    description: string;
    imageURL: string;
    price: number;
    category: string[];
    guide: string;
    coach: string;
    stages: number;
    distance: number;
    unevenness: number;
    bycicleRental: string;
    availability: string;
    tags: string[];
    type: string;
    duration: string;
    routeMap: string;
    details: string;
    journey: string[];
}

//Event interface
export interface Event {
    id: number;
    title: string;
    description: string;
    imageURL: string;
    price: number;
    category: string[];
    difficulty: string;
    guide: string;
    coach: string;
    stages: number;
    distance: number;
    unevenness: number;
    bycicleRental: string;
    availability: string;
    tags: string[];
    type: string;
    duration: string;
    routeMap: string;
    details: string[];
    descriptionRoute1: string[];
    linkRoute1: string;
    imageRoute1: string;
    descriptionRoute2: string[];
    linkRoute2: string;
    imageRoute2: string;
    journey: string[];
}

export interface LoginCredential {
    email: string;
    password: string;
}


export interface RegisterCredential {
    name: string;
    email: string;
    password: string;
}